#if !defined(AFX_XYDCAPACTIVEX_H__D033D057_EF02_41DD_911F_6F7BA69EE270__INCLUDED_)
#define AFX_XYDCAPACTIVEX_H__D033D057_EF02_41DD_911F_6F7BA69EE270__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CXYDCapActiveX wrapper class

class CXYDCapActiveX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CXYDCapActiveX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1a3cb92f, 0x89c0, 0x44b8, { 0x98, 0x2f, 0x94, 0x21, 0xa6, 0x17, 0x1b, 0xb6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AboutBox();
	long Initial();
	long StartRunEx(long DevIndex, long ResWidth, long ResHeight, long RunMode);
	void OpenAutomaticExposure(BOOL bIsOpenAE);
	long Destory();
	long CaptureImage(LPCTSTR FileName);
	long SetImageColorMode(long index);
	void SetImageDPI(long ndpi);
	long SetCurrentDevDPI(float xdpi, float ydpi);
	long AutoCrop(BOOL AdjustSkew);
	long SetBrightness(long BriNum);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_XYDCAPACTIVEX_H__D033D057_EF02_41DD_911F_6F7BA69EE270__INCLUDED_)
