// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "xydcapactivex.h"

/////////////////////////////////////////////////////////////////////////////
// CXYDCapActiveX

IMPLEMENT_DYNCREATE(CXYDCapActiveX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CXYDCapActiveX properties

/////////////////////////////////////////////////////////////////////////////
// CXYDCapActiveX operations

void CXYDCapActiveX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CXYDCapActiveX::Initial()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CXYDCapActiveX::StartRunEx(long DevIndex, long ResWidth, long ResHeight, long RunMode)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		DevIndex, ResWidth, ResHeight, RunMode);
	return result;
}

void CXYDCapActiveX::OpenAutomaticExposure(BOOL bIsOpenAE)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bIsOpenAE);
}

long CXYDCapActiveX::Destory()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CXYDCapActiveX::CaptureImage(LPCTSTR FileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FileName);
	return result;
}

long CXYDCapActiveX::SetImageColorMode(long index)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		index);
	return result;
}

void CXYDCapActiveX::SetImageDPI(long ndpi)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ndpi);
}

long CXYDCapActiveX::SetCurrentDevDPI(float xdpi, float ydpi)
{
	long result;
	static BYTE parms[] =
		VTS_R4 VTS_R4;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		xdpi, ydpi);
	return result;
}

long CXYDCapActiveX::AutoCrop(BOOL AdjustSkew)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		AdjustSkew);
	return result;
}

long CXYDCapActiveX::SetBrightness(long BriNum)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BriNum);
	return result;
}
